workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - when: always


stages:
  - test

run_tests:
  stage: test
  image: python
  before_script:
    pip install -r requirements.txt
  script: pytest -v